# Generated by Django 4.0.6 on 2022-07-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('catid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminservices.category')),
            ],
        ),
        migrations.CreateModel(
            name='Productsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('prodDescription', models.TextField(max_length=500)),
                ('prodStock', models.CharField(default=None, max_length=20)),
                ('prodImage', models.ImageField(upload_to='images/')),
                ('prodPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('prodQuantity', models.BigIntegerField()),
                ('catid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminservices.category')),
                ('subcatid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminservices.subcategory')),
            ],
        ),
    ]
