# Generated by Django 4.0.6 on 2022-07-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0002_subcatesssgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsss',
            name='prodImage',
        ),
    ]
