# Generated by Django 4.0.6 on 2022-07-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0004_delete_subcatesssgory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productsss',
            new_name='Product',
        ),
    ]
