# Generated by Django 4.0.6 on 2022-07-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0005_rename_productsss_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcatid',
        ),
    ]
