# Generated by Django 4.0.6 on 2022-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0008_product_subcatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
