# Generated by Django 4.0.6 on 2022-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0010_rename_prodstock_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
