# Generated by Django 4.0.6 on 2022-10-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0014_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=30)),
                ('adminpass', models.CharField(max_length=300)),
            ],
        ),
    ]
