# Generated by Django 4.0.6 on 2022-10-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0015_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='adminname',
            new_name='adminEmail',
        ),
    ]
