# Generated by Django 4.0.6 on 2022-11-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0017_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
