# Generated by Django 4.0.6 on 2022-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0018_remove_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
