# Generated by Django 4.0.6 on 2022-11-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_reviews_date'),
        ('adminservices', '0019_alter_product_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.order'),
        ),
    ]
