# Generated by Django 4.0.6 on 2022-11-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0021_remove_product_orderid_product_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userid',
        ),
    ]
