# Generated by Django 4.0.6 on 2022-11-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0024_alter_product_prodsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSize',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50),
        ),
    ]
