# Generated by Django 4.0.6 on 2022-11-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
