# Generated by Django 4.0.6 on 2022-11-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0019_alter_product_prod_img'),
        ('app1', '0018_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reviewMsg', models.TextField()),
                ('prodid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminservices.product')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
