# Generated by Django 4.0.6 on 2022-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cart_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('pinCode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
