# Generated by Django 4.0.6 on 2022-10-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
