# Generated by Django 4.0.6 on 2022-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
