# Generated by Django 4.0.6 on 2022-11-02 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0018_remove_product_user'),
        ('app1', '0009_remove_user_address_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('quantity', models.BigIntegerField()),
                ('Payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('Datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('Payment_mode', models.CharField(max_length=20)),
                ('Success_mode', models.CharField(max_length=20)),
                ('Invoice_No', models.BigIntegerField(default=0)),
                ('Razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservices.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
