# Generated by Django 4.0.6 on 2022-11-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
