# Generated by Django 4.0.6 on 2022-11-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contacts',
        ),
    ]
