# Generated by Django 4.0.6 on 2022-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
