# Generated by Django 4.0.6 on 2022-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatesssgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_nasme', models.CharField(max_length=30)),
            ],
        ),
    ]
