# Generated by Django 4.0.6 on 2022-07-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0003_remove_productsss_prodimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCatesssgory',
        ),
    ]
