# Generated by Django 4.0.6 on 2022-11-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_reviews_date'),
        ('adminservices', '0020_product_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderid',
        ),
        migrations.AddField(
            model_name='product',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
