# Generated by Django 4.0.6 on 2022-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0023_product_prodcolor_product_proddescription1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSize',
            field=models.BigIntegerField(),
        ),
    ]
