# Generated by Django 4.1.2 on 2022-11-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0025_alter_product_prodsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodColor',
        ),
    ]
