# Generated by Django 4.1.2 on 2022-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminservices', '0026_remove_product_prodcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodColor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
